# Generated by Django 6.0.7 on 2026-08-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_department_adress_city_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', 'name'], 'verbose_name_plural': 'Address'},
        ),
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
