# Generated by Django 6.0.7 on 2026-07-16 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_size_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
